spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petition
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html